apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ib2h3e2g9-dotnet-basic
  janus-idp.io/tekton: ib2h3e2g9-dotnet-basic
  backstage.io/kubernetes-id: ib2h3e2g9-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ib2h3e2g9-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
